DROP DATABASE IF EXISTS yeticave;

CREATE DATABASE yeticave DEFAULT CHARACTER
SET
  utf8 DEFAULT COLLATE utf8_general_ci;

USE yeticave;

CREATE TABLE users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  email VARCHAR(128) NOT NULL UNIQUE,
  password CHAR(64) NOT NULL,
  name VARCHAR(64) NOT NULL,
  contacts TEXT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE categories (
  id INT AUTO_INCREMENT PRIMARY KEY,
  slug VARCHAR(128) NOT NULL UNIQUE,
  title VARCHAR(128) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE lots (
  id INT AUTO_INCREMENT PRIMARY KEY,
  slug VARCHAR(64) NOT NULL UNIQUE,
  title VARCHAR(128) NOT NULL,
  image VARCHAR(128) NOT NULL,
  description TEXT,
  price_start INT NOT NULL,
  price_step INT NOT NULL,
  expiration_date TIMESTAMP DEFAULT NULL,
  category_id INT DEFAULT NULL,
  user_id INT NOT NULL,
  FOREIGN KEY (category_id) REFERENCES categories (id) ON DELETE SET NULL,
  FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE bets (
  id INT AUTO_INCREMENT PRIMARY KEY,
  price INT NOT NULL,
  user_id INT NOT NULL,
  lot_id INT NOT NULL,
  FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
  FOREIGN KEY (lot_id) REFERENCES lots (id) ON DELETE CASCADE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE FULLTEXT INDEX lot_ft_search ON lots (title, description);

ALTER TABLE lots
ADD COLUMN winner_bet_id INT DEFAULT NULL AFTER user_id,
ADD CONSTRAINT winner_bet_id FOREIGN KEY (winner_bet_id) REFERENCES bets (id) ON DELETE SET NULL;
